### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dco5** [kbytesys/django-recaptcha2#1]
Is there a way to disable to the app for testing? or a way to included in testing?

**Comment by kbytesys** [comment]
This isn't possible atm.

But I can create an env variable that mark the field as "passed" and let you to test your form. 

Something like "RECAPTCHA_DISABLE" that you can enable in your test unit with 

```
os.environ['RECAPTCHA_DISABLE '] = 'True'
```

This is an appropriate solution to your problem?

**Comment by dco5** [comment]
Yes that would work, perfectly. That is what django-recaptcha does.

Thank you!

**Comment by kbytesys** [comment]
Get the new package from pip (or update your code with the last commint) and test if this issue is solved.

Thanks :)
