### ISSUE TITLE
Fails during request.post to Google's siteverify, how to capture logging info?

### ISSUE THREAD

**Issue by marcusamargi** [kbytesys/django-recaptcha2#14]
This is working fine for me on my dev and stage environments. I just launched to a www domain. Recaptcha field renders and can be selected appropriately, but when I submit I get
    
    Connection to reCaptcha server failed

I see that your code logs the exception. How can I capture the log info?

**Comment by kbytesys** [comment]
Hi!

Every I/O exception is logged with

`logger.exception(e)`

You can configure Django logging and look if the issue is caused by your prod env: please follow this link https://docs.djangoproject.com/en/1.11/topics/logging/

**Comment by marcusamargi** [comment]
Thank you for responding.

The problem was with [certifi](https://github.com/certifi/python-certifi) failing to validate "cross-signed certificates". My solution was to remove `certifi`. I also downgraded `requests` to match the version on my dev environment.

Recaptcha is now working in production.

Here's the [relevant issue](https://github.com/certifi/python-certifi/issues/26) for certifi.

----
To track down the problem, I added a catch all logger for errors.

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,

        'filters': {
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse'
            }
        },

        'handlers': {
            'mail_admins': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'class': 'django.utils.log.AdminEmailHandler'
            },

            'error_logfile': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'class': 'logging.FileHandler',
                'filename': Path(PROJECT_DIR, "logs/errors.log"),
            },
        },

        'loggers': {
            'django.request': {
                'handlers': ['mail_admins'],
                'level': 'ERROR',
                'propagate': True,
            },

            '': {
                'handlers': ['error_logfile'],
                'level': 'ERROR',
            },
        }
    }

The log included the following error:

    SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)
