### ISSUE TITLE
reCAPTCHA proxy support

### ISSUE THREAD

**Issue by Xyene** [kbytesys/django-recaptcha2#24]
[recaptcha-init.html](https://github.com/kbytesys/django-recaptcha2/blob/master/snowpenguin/django/recaptcha2/templates/snowpenguin/recaptcha/recaptcha_init.html#L1) loads the reCAPTCHA script from https://google.com, which may be inaccessible for some users (notably, it is blocked in China).

https://recaptcha.net exists [for this purpose](https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally), so it'd be great if there were out-of-the-box support for it (perhaps as a `settings.py` option). Currently we just override the `recaptcha-init` template, but it would be nicer if there was built-in support for it.

I would be happy to send a PR in for this if it'd be helpful.

**Comment by kbytesys** [comment]
If you want to submit a PR for this issue you are welcome! 

I'm a bit busy now and I could add the support to recaptcha.net only after Friday. :(

**Comment by Xyene** [comment]
Submitted https://github.com/kbytesys/django-recaptcha2/pull/26 😄

**Comment by kbytesys** [comment]
PR meged! thanks!
