### ISSUE TITLE
recaptcha_host variable is passed to the wrong tag

### ISSUE THREAD

**Issue by Dwarni** [kbytesys/django-recaptcha2#27]
In the current version of recaptcha2 the recaptcha_host variable is passed to the wrong tag (recaptcha_invisible_button), so recaptcha_init tries to include the api.js from the site directly instead of the value specified in RECAPTCHA_PROXY_HOST or https://google.com

I will do a Pull request which fixes the problem.

**Comment by kbytesys** [comment]
The pull request was accepted, I'm closing this bug
