### ISSUE TITLE
Misunderstanding with backend part in examples.

### ISSUE THREAD

**Issue by s-mx** [kbytesys/django-recaptcha2#7]
It would be nice if you add some information how to validate captcha after submit.

**Comment by kbytesys** [comment]
The recaptcha field acts like other django form fields.

https://docs.djangoproject.com/en/1.10/topics/forms/#the-view

You don't need to validate anything, just check if the form is valid.

**Comment by s-mx** [comment]
Yeah. It's my bad. I'm newbie and it was not obviously for me.
